import type { RpcRegistrationBody, KnobSpec } from './rpc';

// [LAW:decomposition] The single translation seam from an RPC registration to a runnable iTerm2 Python
// stub — the Python-side sibling of src/main/drivers/registrationWire.ts, which maps the same body to
// its wire message. Pure string building, no IO: the IPC boundary owns the file write. Every role's
// Python is a total, unit-testable function of the body.
//
// The emitted surface is verified against the iterm2 Python library source: the RPC / StatusBarRPC /
// TitleProviderRPC / ContextMenuProviderRPC decorators and their async_register signatures, the knob
// classes (Checkbox/String/PositiveFloatingPoint/Color), iterm2.Color (0-255 int components), and
// run_forever(main) as the daemon entry point that keeps a registration alive after it is installed.

const BODY = '    ';

// [LAW:dataflow-not-control-flow] Per-role display text is a value in one table, not a branch.
const ROLE_LABEL: Record<RpcRegistrationBody['role'], string> = {
  generic: 'Generic RPC',
  'status-bar': 'Status bar component',
  'session-title': 'Session title provider',
  'context-menu': 'Context menu provider',
};

export function buildPythonStub(body: RpcRegistrationBody): string {
  // The role block is authored at module scope (no indentation) and shifted one level to sit inside
  // main(connection); blank lines stay blank rather than becoming trailing whitespace.
  const block = buildRoleBlock(body).map((line) => (line ? BODY + line : line));
  return (
    [
      '#!/usr/bin/env python3',
      `"""${ROLE_LABEL[body.role]} stub: ${pyIdentifier(body.name)}`,
      '',
      'Generated by iTerm2 Scripting Helper. Drop this in',
      '~/Library/Application Support/iTerm2/Scripts/ and run it from the iTerm2',
      'Scripts menu, then fill in the function body with your own logic.',
      '"""',
      'import iterm2',
      '',
      '',
      'async def main(connection):',
      ...block,
      '',
      '',
      'iterm2.run_forever(main)',
    ].join('\n') + '\n'
  );
}

// Exhaustive over the RPC roles: each role emits its own decorator, signature, and registration call.
// There is no fall-through arm — a new RPC role makes this a compile error, never a silent empty stub.
function buildRoleBlock(body: RpcRegistrationBody): string[] {
  const name = pyIdentifier(body.name);
  const ret = jsonToPython(body.responseTemplate);
  switch (body.role) {
    case 'generic': {
      const timeout = body.timeout > 0 ? `, timeout=${body.timeout}` : '';
      return [
        '@iterm2.RPC',
        `async def ${name}(${buildParams(body)}):`,
        `${BODY}return ${ret}`,
        '',
        `await ${name}.async_register(connection${timeout})`,
      ];
    }
    case 'session-title':
      return displayIdentityBlock('TitleProviderRPC', name, buildParams(body), ret, body.attrs);
    case 'context-menu':
      return displayIdentityBlock('ContextMenuProviderRPC', name, buildParams(body), ret, body.attrs);
    case 'status-bar': {
      const params = buildParams(body);
      const signature = params ? `knobs, ${params}` : 'knobs';
      return [
        'component = iterm2.StatusBarComponent(',
        `${BODY}short_description=${pyStr(body.attrs.shortDescription)},`,
        `${BODY}detailed_description=${pyStr(body.attrs.detailedDescription)},`,
        ...knobsLines(body.attrs.knobs),
        `${BODY}exemplar=${pyStr(body.attrs.exemplar)},`,
        `${BODY}update_cadence=${body.attrs.updateCadence > 0 ? String(body.attrs.updateCadence) : 'None'},`,
        `${BODY}identifier=${pyStr(body.attrs.uniqueIdentifier)},`,
        `${BODY}format=iterm2.StatusBarComponent.Format.${body.attrs.format},`,
        ')',
        '',
        '@iterm2.StatusBarRPC',
        `async def ${name}(${signature}):`,
        `${BODY}return ${ret}`,
        '',
        `await component.async_register(connection, ${name})`,
      ];
    }
  }
  // [LAW:types-are-the-program] Reachable only if a new RPC role escapes the switch; the never
  // assignment makes that a compile error instead of a silently empty Python file.
  return assertExhaustedRole(body);
}

// [LAW:one-type-per-behavior] Title and context-menu providers register identically — same attrs, same
// async_register shape — differing only in the decorator value, so they are one builder, not two.
function displayIdentityBlock(
  decorator: 'TitleProviderRPC' | 'ContextMenuProviderRPC',
  name: string,
  params: string,
  ret: string,
  attrs: { displayName: string; uniqueIdentifier: string },
): string[] {
  return [
    `@iterm2.${decorator}`,
    `async def ${name}(${params}):`,
    `${BODY}return ${ret}`,
    '',
    `await ${name}.async_register(`,
    `${BODY}connection,`,
    `${BODY}display_name=${pyStr(attrs.displayName)},`,
    `${BODY}unique_identifier=${pyStr(attrs.uniqueIdentifier)},`,
    ')',
  ];
}

// The function signature's parameters. An argument bound to a variable (a default) is expressed as the
// iterm2.Reference default the API expects; an unbound argument is a plain parameter. Python requires
// defaulted parameters last, so the unbound ones lead — safe because iTerm2 invokes RPCs by name.
function buildParams(body: { arguments: string[]; defaults: Array<{ name: string; path: string }> }): string {
  const referencePath = new Map(body.defaults.map((d) => [d.name, d.path]));
  const plain: string[] = [];
  const referenced: string[] = [];
  for (const arg of body.arguments) {
    const path = referencePath.get(arg);
    if (path === undefined) plain.push(pyIdentifier(arg));
    else referenced.push(`${pyIdentifier(arg)}=iterm2.Reference(${pyStr(path)})`);
  }
  return [...plain, ...referenced].join(', ');
}

function knobsLines(knobs: readonly KnobSpec[]): string[] {
  if (knobs.length === 0) return [`${BODY}knobs=[],`];
  return [
    `${BODY}knobs=[`,
    ...knobs.map((k) => `${BODY}${BODY}${buildKnob(k)},`),
    `${BODY}],`,
  ];
}

// Exhaustive over knob types: each maps to its iterm2 knob class with that class's verified argument
// order. A new knob type is a compile error here, never an omitted or mistyped knob.
function buildKnob(k: KnobSpec): string {
  switch (k.type) {
    case 'Checkbox':
      return `iterm2.CheckboxKnob(${pyStr(k.name)}, ${pyBool(k.jsonDefaultValue)}, ${pyStr(k.key)})`;
    case 'String':
      return `iterm2.StringKnob(${pyStr(k.name)}, ${pyStr(k.placeholder)}, ${pyStringDefault(k.jsonDefaultValue)}, ${pyStr(k.key)})`;
    case 'PositiveFloatingPoint':
      return `iterm2.PositiveFloatingPointKnob(${pyStr(k.name)}, ${pyFloat(k.jsonDefaultValue)}, ${pyStr(k.key)})`;
    case 'Color':
      return `iterm2.ColorKnob(${pyStr(k.name)}, ${pyColor(k.jsonDefaultValue)}, ${pyStr(k.key)})`;
  }
  // KnobSpec is a flat interface, so the discriminant — not the object — is what the cases exhaust.
  return assertExhaustedKnob(k.type);
}

// A JSON-encoded string of double-quoted ASCII/unicode is a valid Python string literal verbatim, so
// the producer is JSON.stringify — quotes, backslashes, and newlines are escaped identically.
function pyStr(s: string): string {
  return JSON.stringify(s);
}

function pyIdentifier(raw: string): string {
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

// A JSON value rendered as the equivalent Python literal. Invalid or absent JSON becomes None — the
// honest "no value", never a thrown error mid-build.
function jsonToPython(jsonText: string): string {
  let value: unknown;
  try {
    value = JSON.parse(jsonText);
  } catch {
    return 'None';
  }
  return literalToPython(value);
}

function literalToPython(v: unknown): string {
  if (v === null) return 'None';
  if (typeof v === 'boolean') return v ? 'True' : 'False';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'None';
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(literalToPython).join(', ')}]`;
  if (typeof v === 'object') {
    const entries = Object.entries(v as Record<string, unknown>).map(
      ([k, val]) => `${JSON.stringify(k)}: ${literalToPython(val)}`,
    );
    return `{${entries.join(', ')}}`;
  }
  return 'None';
}

function pyBool(jsonText: string): string {
  try {
    return JSON.parse(jsonText) === true ? 'True' : 'False';
  } catch {
    return 'False';
  }
}

function pyStringDefault(jsonText: string): string {
  try {
    const v = JSON.parse(jsonText);
    return pyStr(typeof v === 'string' ? v : jsonText);
  } catch {
    return pyStr(jsonText);
  }
}

function pyFloat(jsonText: string): string {
  try {
    const v = JSON.parse(jsonText);
    return typeof v === 'number' && Number.isFinite(v) ? String(v) : '0.0';
  } catch {
    return '0.0';
  }
}

// The color knob default is iTerm2's component dictionary (0-1 floats keyed "Red Component" etc.);
// iterm2.Color takes 0-255 int components, so each is scaled and clamped. Missing components fall to
// opaque black, matching iterm2.Color's own defaults.
function pyColor(jsonText: string): string {
  let obj: Record<string, unknown> = {};
  try {
    const parsed = JSON.parse(jsonText);
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      obj = parsed as Record<string, unknown>;
    }
  } catch {
    obj = {};
  }
  const comp = (key: string, dflt: number): number => {
    const v = obj[key];
    const n = typeof v === 'number' ? v : dflt;
    return Math.max(0, Math.min(255, Math.round(n * 255)));
  };
  return `iterm2.Color(${comp('Red Component', 0)}, ${comp('Green Component', 0)}, ${comp('Blue Component', 0)}, ${comp('Alpha Component', 1)})`;
}

function assertExhaustedRole(body: never): never {
  throw new Error(`Unhandled RPC role: ${JSON.stringify(body)}`);
}

function assertExhaustedKnob(type: never): never {
  throw new Error(`Unhandled knob type: ${JSON.stringify(type)}`);
}
