import type { RpcRegistrationBody, KnobSpec } from './rpc';

// [LAW:decomposition] The single translation seam from an RPC registration to a runnable iTerm2 Python
// stub — the Python-side sibling of src/main/drivers/registrationWire.ts, which maps the same body to
// its wire message. Pure string building, no IO: the IPC boundary owns the file write. Every role's
// Python is a total, unit-testable function of the body.
//
// The emitted surface is verified against the iterm2 Python library source: the RPC / StatusBarRPC /
// TitleProviderRPC / ContextMenuProviderRPC decorators and their async_register signatures, the knob
// classes (Checkbox/String/PositiveFloatingPoint/Color), iterm2.Color (0-255 int components), and
// run_forever(main) as the daemon entry point that keeps a registration alive after it is installed.

const BODY = '    ';

// [LAW:dataflow-not-control-flow] Per-role display text is a value in one table, not a branch.
const ROLE_LABEL: Record<RpcRegistrationBody['role'], string> = {
  generic: 'Generic RPC',
  'status-bar': 'Status bar component',
  'session-title': 'Session title provider',
  'context-menu': 'Context menu provider',
};

export function buildPythonStub(body: RpcRegistrationBody): string {
  // The role block is authored at module scope (no indentation) and shifted one level to sit inside
  // main(connection); blank lines stay blank rather than becoming trailing whitespace.
  const block = buildRoleBlock(body).map((line) => (line ? BODY + line : line));
  return (
    [
      '#!/usr/bin/env python3',
      `"""${ROLE_LABEL[body.role]} stub: ${pyIdentifier(body.name)}`,
      '',
      'Generated by iTerm2 Scripting Helper. Drop this in',
      '~/Library/Application Support/iTerm2/Scripts/ and run it from the iTerm2',
      'Scripts menu, then fill in the function body with your own logic.',
      '"""',
      'import iterm2',
      '',
      '',
      'async def main(connection):',
      ...block,
      '',
      '',
      'iterm2.run_forever(main)',
    ].join('\n') + '\n'
  );
}

// [LAW:one-source-of-truth] The default export filename derives from the same sanitized identifier the
// stub's function uses, so a name with slashes or spaces can never yield a bad save path. An empty name
// (the editor degenerate case) falls back to a friendly default rather than the bare "_".
export function pythonStubFileName(body: RpcRegistrationBody): string {
  const base = body.name.trim() ? pyIdentifier(body.name) : 'rpc_stub';
  return `${base}.py`;
}

// Exhaustive over the RPC roles: each role emits its own decorator, signature, and registration call.
// There is no fall-through arm — a new RPC role makes this a compile error, never a silent empty stub.
function buildRoleBlock(body: RpcRegistrationBody): string[] {
  const name = pyIdentifier(body.name);
  const ret = jsonToPython(body.responseTemplate, 'response template');
  switch (body.role) {
    case 'generic': {
      const timeout = body.timeout > 0 ? `, timeout=${body.timeout}` : '';
      return [
        '@iterm2.RPC',
        `async def ${name}(${buildParams(body)}):`,
        `${BODY}return ${ret}`,
        '',
        `await ${name}.async_register(connection${timeout})`,
      ];
    }
    case 'session-title':
      return displayIdentityBlock('TitleProviderRPC', name, buildParams(body), ret, body.attrs, body.timeout);
    case 'context-menu':
      return displayIdentityBlock('ContextMenuProviderRPC', name, buildParams(body), ret, body.attrs, body.timeout);
    case 'status-bar': {
      const params = buildParams(body);
      const signature = params ? `knobs, ${params}` : 'knobs';
      return [
        'component = iterm2.StatusBarComponent(',
        `${BODY}short_description=${pyStr(body.attrs.shortDescription)},`,
        `${BODY}detailed_description=${pyStr(body.attrs.detailedDescription)},`,
        ...knobsLines(body.attrs.knobs),
        `${BODY}exemplar=${pyStr(body.attrs.exemplar)},`,
        `${BODY}update_cadence=${body.attrs.updateCadence > 0 ? String(body.attrs.updateCadence) : 'None'},`,
        `${BODY}identifier=${pyStr(body.attrs.uniqueIdentifier)},`,
        `${BODY}format=iterm2.StatusBarComponent.Format.${body.attrs.format},`,
        ')',
        '',
        '@iterm2.StatusBarRPC',
        `async def ${name}(${signature}):`,
        `${BODY}return ${ret}`,
        '',
        `await component.async_register(connection, ${name})`,
      ];
    }
  }
  // [LAW:types-are-the-program] Reachable only if a new RPC role escapes the switch; the never
  // assignment makes that a compile error instead of a silently empty Python file.
  return assertExhaustedRole(body);
}

// [LAW:one-type-per-behavior] Title and context-menu providers register identically — same attrs, same
// async_register shape (both accept the optional timeout) — differing only in the decorator value, so
// they are one builder, not two. The authored timeout is preserved when set, dropped (defaulting to
// the API's None) when zero, exactly as the generic arm handles it.
function displayIdentityBlock(
  decorator: 'TitleProviderRPC' | 'ContextMenuProviderRPC',
  name: string,
  params: string,
  ret: string,
  attrs: { displayName: string; uniqueIdentifier: string },
  timeout: number,
): string[] {
  return [
    `@iterm2.${decorator}`,
    `async def ${name}(${params}):`,
    `${BODY}return ${ret}`,
    '',
    `await ${name}.async_register(`,
    `${BODY}connection,`,
    `${BODY}display_name=${pyStr(attrs.displayName)},`,
    `${BODY}unique_identifier=${pyStr(attrs.uniqueIdentifier)},`,
    ...(timeout > 0 ? [`${BODY}timeout=${timeout},`] : []),
    ')',
  ];
}

// The function signature's parameters. An argument bound to a variable (a default) is expressed as the
// iterm2.Reference default the API expects; an unbound argument is a plain parameter. Python requires
// defaulted parameters last, so the unbound ones lead — safe because iTerm2 invokes RPCs by name.
function buildParams(body: { arguments: string[]; defaults: Array<{ name: string; path: string }> }): string {
  const referencePath = new Map(body.defaults.map((d) => [d.name, d.path]));
  const plain: string[] = [];
  const referenced: string[] = [];
  for (const arg of body.arguments) {
    const path = referencePath.get(arg);
    if (path === undefined) plain.push(pyIdentifier(arg));
    else referenced.push(`${pyIdentifier(arg)}=iterm2.Reference(${pyStr(path)})`);
  }
  return [...plain, ...referenced].join(', ');
}

function knobsLines(knobs: readonly KnobSpec[]): string[] {
  if (knobs.length === 0) return [`${BODY}knobs=[],`];
  return [
    `${BODY}knobs=[`,
    ...knobs.map((k) => `${BODY}${BODY}${buildKnob(k)},`),
    `${BODY}],`,
  ];
}

// Exhaustive over knob types: each maps to its iterm2 knob class with that class's verified argument
// order. A new knob type is a compile error here, never an omitted or mistyped knob. The default value
// is parsed once; a malformed default throws rather than coercing to a silent fallback.
function buildKnob(k: KnobSpec): string {
  // [LAW:no-silent-failure] The default is parsed once and then checked against the knob's type; a
  // value of the wrong type is an authoring error that throws, never a fallback that silently changes
  // the exported knob.
  const label = `knob "${k.name}" default value`;
  const def = parseJson(k.jsonDefaultValue, label);
  switch (k.type) {
    case 'Checkbox':
      return `iterm2.CheckboxKnob(${pyStr(k.name)}, ${expectBoolean(def, label) ? 'True' : 'False'}, ${pyStr(k.key)})`;
    case 'String':
      return `iterm2.StringKnob(${pyStr(k.name)}, ${pyStr(k.placeholder)}, ${pyStr(expectString(def, label))}, ${pyStr(k.key)})`;
    case 'PositiveFloatingPoint':
      return `iterm2.PositiveFloatingPointKnob(${pyStr(k.name)}, ${String(expectNumber(def, label))}, ${pyStr(k.key)})`;
    case 'Color':
      return `iterm2.ColorKnob(${pyStr(k.name)}, ${colorLiteral(def, label)}, ${pyStr(k.key)})`;
  }
  // KnobSpec is a flat interface, so the discriminant — not the object — is what the cases exhaust.
  return assertExhaustedKnob(k.type);
}

function expectBoolean(v: unknown, label: string): boolean {
  if (typeof v !== 'boolean') throw new Error(`${label} must be a boolean`);
  return v;
}

function expectString(v: unknown, label: string): string {
  if (typeof v !== 'string') throw new Error(`${label} must be a string`);
  return v;
}

function expectNumber(v: unknown, label: string): number {
  if (typeof v !== 'number' || !Number.isFinite(v)) throw new Error(`${label} must be a number`);
  return v;
}

// A JSON-encoded string of double-quoted ASCII/unicode is a valid Python string literal verbatim, so
// the producer is JSON.stringify — quotes, backslashes, and newlines are escaped identically.
function pyStr(s: string): string {
  return JSON.stringify(s);
}

// Python's reserved words (keyword.kwlist) — a def or parameter named after one of these is a syntax
// error, so a sanitized name colliding with a keyword is suffixed, the PEP 8 convention (e.g. class_).
const PYTHON_KEYWORDS: ReadonlySet<string> = new Set([
  'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue',
  'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in',
  'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield',
]);

function pyIdentifier(raw: string): string {
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, '_');
  const valid = /^[A-Za-z_]/.test(cleaned) ? cleaned : `_${cleaned}`;
  return PYTHON_KEYWORDS.has(valid) ? `${valid}_` : valid;
}

// [LAW:no-silent-failure] The single fallible step: a value that does not parse as JSON is a real
// authoring error (an invalid response template, a malformed knob default), surfaced as a loud throw
// the IPC boundary turns into a returned error — never coerced into a stub whose meaning silently
// differs from what the user wrote.
function parseJson(jsonText: string, label: string): unknown {
  try {
    return JSON.parse(jsonText);
  } catch (err) {
    throw new Error(`${label} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`);
  }
}

// A JSON value rendered as the equivalent Python literal.
function jsonToPython(jsonText: string, label: string): string {
  return literalToPython(parseJson(jsonText, label));
}

function literalToPython(v: unknown): string {
  if (v === null) return 'None';
  if (typeof v === 'boolean') return v ? 'True' : 'False';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'None';
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(literalToPython).join(', ')}]`;
  if (typeof v === 'object') {
    const entries = Object.entries(v as Record<string, unknown>).map(
      ([k, val]) => `${JSON.stringify(k)}: ${literalToPython(val)}`,
    );
    return `{${entries.join(', ')}}`;
  }
  return 'None';
}

// The color knob default is iTerm2's component dictionary (0-1 floats keyed "Red Component" etc.);
// iterm2.Color takes 0-255 int components, so each present component is scaled and clamped. A non-object
// default, or a present component that is not a number, throws ([LAW:no-silent-failure]); a genuinely
// absent component falls to iterm2.Color's own default (opaque black) rather than being invented.
function colorLiteral(def: unknown, label: string): string {
  if (!def || typeof def !== 'object' || Array.isArray(def)) {
    throw new Error(`${label} must be a color component object`);
  }
  const obj = def as Record<string, unknown>;
  const comp = (key: string, fallback: number): number => {
    const v = obj[key];
    if (v === undefined) return fallback;
    if (typeof v !== 'number') throw new Error(`${label} "${key}" must be a number`);
    return Math.max(0, Math.min(255, Math.round(v * 255)));
  };
  return `iterm2.Color(${comp('Red Component', 0)}, ${comp('Green Component', 0)}, ${comp('Blue Component', 0)}, ${comp('Alpha Component', 255)})`;
}

function assertExhaustedRole(body: never): never {
  throw new Error(`Unhandled RPC role: ${JSON.stringify(body)}`);
}

function assertExhaustedKnob(type: never): never {
  throw new Error(`Unhandled knob type: ${JSON.stringify(type)}`);
}
