import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildPythonStub, pythonStubFileName } from './pythonStub';
import type { RpcRegistrationBody, KnobSpec } from './rpc';

const rpcCommon = {
  name: 'my_rpc',
  arguments: ['session_id', 'count'],
  defaults: [{ name: 'session_id', path: 'id' }],
  timeout: 5,
  responseTemplate: '"ok"',
};

const allKnobs: KnobSpec[] = [
  { name: 'enabled', type: 'Checkbox', placeholder: '', jsonDefaultValue: 'true', key: 'enabled' },
  { name: 'label', type: 'String', placeholder: 'type here', jsonDefaultValue: '"hi"', key: 'label' },
  { name: 'rate', type: 'PositiveFloatingPoint', placeholder: '', jsonDefaultValue: '1.5', key: 'rate' },
  {
    name: 'tint',
    type: 'Color',
    placeholder: 'Pick',
    jsonDefaultValue: JSON.stringify({
      'Red Component': 0.2,
      'Green Component': 0.6,
      'Blue Component': 1,
      'Alpha Component': 1,
    }),
    key: 'tint',
  },
];

function bodyFor(role: RpcRegistrationBody['role']): RpcRegistrationBody {
  switch (role) {
    case 'generic':
      return { ...rpcCommon, role: 'generic' };
    case 'status-bar':
      return {
        ...rpcCommon,
        role: 'status-bar',
        attrs: {
          shortDescription: 'short',
          detailedDescription: 'detail',
          knobs: allKnobs,
          exemplar: '12:34',
          updateCadence: 5,
          uniqueIdentifier: 'com.example.sb',
          format: 'HTML',
        },
      };
    case 'session-title':
      return {
        ...rpcCommon,
        role: 'session-title',
        attrs: { displayName: 'Upper Case', uniqueIdentifier: 'com.example.title' },
      };
    case 'context-menu':
      return {
        ...rpcCommon,
        role: 'context-menu',
        attrs: { displayName: 'My Action', uniqueIdentifier: 'com.example.context' },
      };
  }
}

// [LAW:verifiable-goals] Completeness gate, the same idiom as registrationWire.test.ts: every RPC role
// must produce a stub carrying its decorator and registration call. The Record type fails the compile
// when a role is missing; the runtime check makes the gap a named test failure too.
const CASES: Record<RpcRegistrationBody['role'], () => void> = {
  generic: () => {
    // Exact lock on the whole file: the shebang, docstring, reference-bound argument ordering
    // (unbound args lead), the response literal, the timeout, and run_forever(main) as the entry.
    expect(buildPythonStub(bodyFor('generic'))).toBe(
      `#!/usr/bin/env python3
"""Generic RPC stub: my_rpc

Generated by iTerm2 Scripting Helper. Drop this in
~/Library/Application Support/iTerm2/Scripts/ and run it from the iTerm2
Scripts menu, then fill in the function body with your own logic.
"""
import iterm2


async def main(connection):
    @iterm2.RPC
    async def my_rpc(count, session_id=iterm2.Reference("id")):
        return "ok"

    await my_rpc.async_register(connection, timeout=5)


iterm2.run_forever(main)
`,
    );
  },
  'status-bar': () => {
    const src = buildPythonStub(bodyFor('status-bar'));
    expect(src).toContain('@iterm2.StatusBarRPC');
    expect(src).toContain('async def my_rpc(knobs, count, session_id=iterm2.Reference("id")):');
    expect(src).toContain('await component.async_register(connection, my_rpc)');
    expect(src).toContain('update_cadence=5,');
    expect(src).toContain('format=iterm2.StatusBarComponent.Format.HTML,');
    // Each knob class with its verified argument order; the color is scaled from 0-1 to 0-255.
    expect(src).toContain('iterm2.CheckboxKnob("enabled", True, "enabled"),');
    expect(src).toContain('iterm2.StringKnob("label", "type here", "hi", "label"),');
    expect(src).toContain('iterm2.PositiveFloatingPointKnob("rate", 1.5, "rate"),');
    expect(src).toContain('iterm2.ColorKnob("tint", iterm2.Color(51, 153, 255, 255), "tint"),');
  },
  'session-title': () => {
    const src = buildPythonStub(bodyFor('session-title'));
    expect(src).toContain('@iterm2.TitleProviderRPC');
    expect(src).toContain('display_name="Upper Case",');
    expect(src).toContain('unique_identifier="com.example.title",');
    expect(src).toContain('timeout=5,');
    expect(src).toContain('await my_rpc.async_register(');
  },
  'context-menu': () => {
    const src = buildPythonStub(bodyFor('context-menu'));
    expect(src).toContain('@iterm2.ContextMenuProviderRPC');
    expect(src).toContain('display_name="My Action",');
    expect(src).toContain('unique_identifier="com.example.context",');
    expect(src).toContain('timeout=5,');
  },
};

describe('buildPythonStub', () => {
  for (const [role, check] of Object.entries(CASES)) {
    it(`builds a ${role} stub`, check);
  }

  it('emits an empty knob list and omits a zero cadence/timeout cleanly', () => {
    const src = buildPythonStub({
      role: 'status-bar',
      name: 'bare',
      arguments: [],
      defaults: [],
      timeout: 0,
      responseTemplate: '"x"',
      attrs: {
        shortDescription: '',
        detailedDescription: '',
        knobs: [],
        exemplar: '',
        updateCadence: 0,
        uniqueIdentifier: 'com.example.bare',
        format: 'PLAIN_TEXT',
      },
    });
    expect(src).toContain('knobs=[],');
    expect(src).toContain('update_cadence=None,');
    expect(src).toContain('async def bare(knobs):');
  });

  it('throws on an invalid response template rather than silently emitting None', () => {
    expect(() =>
      buildPythonStub({ ...rpcCommon, role: 'generic', responseTemplate: 'not json' }),
    ).toThrow(/response template is not valid JSON/);
  });

  it('throws on a malformed knob default rather than coercing it', () => {
    expect(() =>
      buildPythonStub({
        ...rpcCommon,
        role: 'status-bar',
        attrs: {
          shortDescription: '',
          detailedDescription: '',
          knobs: [{ name: 'rate', type: 'PositiveFloatingPoint', placeholder: '', jsonDefaultValue: 'oops', key: 'rate' }],
          exemplar: '',
          updateCadence: 0,
          uniqueIdentifier: 'com.example.x',
          format: 'PLAIN_TEXT',
        },
      }),
    ).toThrow(/knob "rate" default value is not valid JSON/);
  });

  it('throws on a valid-JSON knob default of the wrong type rather than coercing it', () => {
    const withKnob = (knob: KnobSpec) =>
      buildPythonStub({
        ...rpcCommon,
        role: 'status-bar',
        attrs: {
          shortDescription: '',
          detailedDescription: '',
          knobs: [knob],
          exemplar: '',
          updateCadence: 0,
          uniqueIdentifier: 'com.example.x',
          format: 'PLAIN_TEXT',
        },
      });
    expect(() =>
      withKnob({ name: 'rate', type: 'PositiveFloatingPoint', placeholder: '', jsonDefaultValue: '"hi"', key: 'rate' }),
    ).toThrow(/knob "rate" default value must be a number/);
    expect(() =>
      withKnob({ name: 'on', type: 'Checkbox', placeholder: '', jsonDefaultValue: '1', key: 'on' }),
    ).toThrow(/knob "on" default value must be a boolean/);
    expect(() =>
      withKnob({ name: 'tint', type: 'Color', placeholder: '', jsonDefaultValue: '"red"', key: 'tint' }),
    ).toThrow(/knob "tint" default value must be a color component object/);
  });

  it('sanitizes a non-identifier function name', () => {
    const src = buildPythonStub({ ...rpcCommon, role: 'generic', name: '2 bad-name' });
    expect(src).toContain('async def _2_bad_name(');
  });

  it('suffixes Python keywords used as a function name or argument', () => {
    const src = buildPythonStub({
      ...rpcCommon,
      role: 'generic',
      name: 'class',
      arguments: ['return', 'ok'],
      defaults: [],
    });
    expect(src).toContain('async def class_(return_, ok):');
    expect(src).toContain('await class_.async_register(');
  });

  it('derives the default filename from the sanitized identifier, never the raw name', () => {
    expect(pythonStubFileName({ ...rpcCommon, role: 'generic', name: 'a/b name' })).toBe('a_b_name.py');
    expect(pythonStubFileName({ ...rpcCommon, role: 'generic', name: '   ' })).toBe('rpc_stub.py');
  });
});

// [LAW:verifiable-goals] The acceptance bar is "an exported stub runs unchanged in the Scripts folder".
// The deterministic proxy: every generated stub is valid Python 3 (py_compile parses and byte-compiles
// it without importing iterm2). Skips loudly with a reason if python3 is unavailable, never silently.
describe('generated stubs are valid Python 3', () => {
  const python = (() => {
    try {
      execFileSync('python3', ['--version'], { stdio: 'ignore' });
      return 'python3';
    } catch {
      return null;
    }
  })();

  const dir = mkdtempSync(join(tmpdir(), 'pystub-'));
  const roles: RpcRegistrationBody['role'][] = [
    'generic',
    'status-bar',
    'session-title',
    'context-menu',
  ];

  for (const role of roles) {
    it.skipIf(python === null)(`${role} stub compiles`, () => {
      const file = join(dir, `${role}.py`);
      writeFileSync(file, buildPythonStub(bodyFor(role)), 'utf8');
      expect(() =>
        execFileSync(python as string, ['-m', 'py_compile', file], { stdio: 'pipe' }),
      ).not.toThrow();
    });
  }
});
